name: DiscordEasyWhitelist
version: '2.1.0'
main: me.animepdf.dew.DiscordEasyWhitelist
description: Manage SimpleWhitelist with DiscordSRV integration
author: Animepdf
website: https://github.com/Anime-pdf/DiscordEasyWhitelist
api-version: '1.21'
load: POSTWORLD
depend: [ DiscordSRV, simplewhitelist ]