name: Publish JARs

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew build
      - name: Upload Built JARs
        uses: actions/upload-artifact@v4
        with:
          name: built-jars
          path: |
            ./build/libs/*.jar

  distribute:
    needs: build
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Built JARs
        uses: actions/download-artifact@v4
        with:
          name: built-jars
          path: ./build
      - name: Publish to GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          files: |
            build/*.jar
          loaders: |
            paper
            purpur
            folia
          game-versions: |
            >=1.21.8
          version: ${{ github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
